version: '2'

services:
  pihole:
    extends:
      service: pihole
      file: dns/docker-compose.yaml
    networks:
      home:
        # Your new IP - can be anything
        ipv4_address: 192.168.1.XXX

networks:
  home:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        # no idea... but works
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip_range: 192.168.1.192/28
